* 웹 브라우저 원격조작할 때 사용하는 도구
* 웹 어플리케이션 테스트를 자동화할 때 사용
* 엄청 느림

In [6]:
import numpy as np

np.full((3,2), 7)


array([[7, 7],
       [7, 7],
       [7, 7]])

In [27]:
from scipy import sparse

matrix = np.array([[0,0],
                  [0,1],
                  [3,0]])

matrix
# 0이 아닌 값만 출력
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

new_sparse = sparse.csc_matrix(([1,3],([1,2],[1,0])), shape=(3,10))
print(new_sparse)
new_sparse.toarray()

  (1, 1)	1
  (2, 0)	3
  (2, 0)	3
  (1, 1)	1


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [34]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix[[0,2],[1,0]] # 0행 1열, 2행 0열

array([2, 7])

In [44]:
matrix
add_100 = lambda i : i+100

vectorized_add_100 = np.vectorize(add_100)
print(vectorized_add_100(matrix))
print('\n')
print(matrix + 100)
print('\n')
print(matrix + [100,100,100])
print('\n')
print(matrix + [[100],[100],[100]])


[[101 102 103]
 [104 105 106]
 [107 108 109]]


[[101 102 103]
 [104 105 106]
 [107 108 109]]


[[101 102 103]
 [104 105 106]
 [107 108 109]]


[[101 102 103]
 [104 105 106]
 [107 108 109]]


In [49]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
vector_column = np.max(matrix, axis = 1, keepdims=True)
vector_column
np.mean(matrix)
np.var(matrix)
np.std(matrix)

2.581988897471611

In [64]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
matrix.size
matrix.reshape(2,6)
matrix.reshape(1,-1)
matrix.reshape(12)
matrix.reshape(-1)
matrix.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [65]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [74]:
matrix = np.array([ [ [1, 2] ,[ 3, 4 ], [5, 6]  ],
            [ [7, 8 ], [9, 10 ], [11, 12] ] ])  #2x3x2 행렬
print(matrix.shape)
matrix.transpose((0, 2, 1))  #2x2x3 행렬로 변환


(2, 3, 2)


array([[[ 1,  3,  5],
        [ 2,  4,  6]],

       [[ 7,  9, 11],
        [ 8, 10, 12]]])

In [79]:
matrix = np.array( [ [ 1, 2, 3],  [ 4, 5, 6], [ 7, 8, 9]  ])
matrix.flatten()
matrix.reshape(1, -1)
vector_reshaped = matrix.reshape( -1)
vector_flattened = matrix.flatten()
matrix[0][0] = -1
vector_reshaped 
vector_flattened 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
matrix = np.array( [ [ 1, 1, 1],  [ 1, 1, 10], [ 1, 1, 15]  ])
np.linalg.matrix_rank(matrix)  #행렬은 첫번째 열과 두번째 열이 동일하기 때문에 독립적인 열이 2개
s = np.linalg.svd(matrix, compute_uv = False)  #svd 함수로 특잇값만 계산
np.sum(s > 1e-10)  #오차를 고려하여 0에 가까운 아주 작은 값을 지정


2

In [93]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.dot(a,b)
a@b

np.matmul(a,b)


32

ModuleNotFoundError: No module named 'cx_Oracle'